# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    security.access.building_voter:
        class: BubbleDiagramBundle\Security\BuildingVoter
        tags:
            - { name: security.voter }
        public: false

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
