<?php

namespace BubbleDiagramBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
//    public function findUsersByTeam($teamId) {
//        $dql = "SELECT user FROM BubbleDiagramBundle:User user
//                                    JOIN team ON 
//                                    WHERE "
//    }
}
